version: '3'

services:
  db:
    container_name: mysql_database
    image: mysql:oracle
    volumes:
      # - mysql-db:/var/lib/
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db

# volumes:
#   mysql-db:
#     external: true