
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-restserver
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      USER_DB: ${USER_DB}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    restart: always
  
  db:
    container_name: mysql_database
    image: mysql:oracle
    volumes:
      # - mysql-db:/var/lib/
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_PASSWORD}
    restart: always

  phpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db
    restart: always

# volumes:
#   mysql-db:
#     external: true